#!/usr/bin/env bash
# Display the contents of the current directory in list format.
#   Only displays the parts of the name after the first dash.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
